stukowin: ceus_importer Class Reference
ceus_importer Class Reference
CEUS2Drupal
Imports data from CEUS and stores it in the Drupal database.
Public Member Functions
__construct ()
Constructor.
connect ()
Connect to CEUS and receive Authtoken.
get_curricula ()
Main method: Imports curriculum data from CEUS.
get_error ()
Returns last error message.
Private Member Functions
check_return_value ($sReturn)
Checks the JSON returned by the CEUS API.
get_detail ($iID)
Fetches a single course from CEUS.
save_node ($aDetail, $tid)
Saves a course as a Drupal content node.
has_relation ($sRelationfield)
Checks if a course has recommendations or prerequisites.
parse_link_term_code ($sLink)
Parses linked web page and tries to extract a course code.
find_nodeid_by_field ($sFieldtype, $sFieldcontent)
Looks for Drupal content node by title or code.
get_term_ids ($sRelationfield)
Parses the voraussetzungen field of a course and tries to extract the relation.
process_relations ()
Creates Drupal relations out of CEUS relations.
get_details ($aTree, $iParentID, $iCurriculumID)
Recursive function that traverses a curriculum tree.
check_vocabulary ($aCurriculum)
Checks if a taxonomy vocabulary for the given curriculum exists and creates it if not.
get_curricula_list ()
Gets a list of all curricula (bachelor, master) from CEUS.
get_curriculum ($iID)
Gets one curriculum tree from CEUS.
Private Attributes
$sCeusUrl
Complete URL to CEUS API.
$sUsername
Username for CEUS API.
$sPassword
Password for CEUS API.
$sAuthtoken
CEUS authentication token.
$aFiles
Names of the API methods.
$sError
Error message.
$aLanguage
All supported languages.
$aVocabulary
All vocabularies for current curricula.
$aTerms
All Terms for vocabularies.
$aStats
Import statistics.
$aRelations
Relations of every course (if available)
Detailed Description
Imports data from CEUS and stores it in the Drupal database.
This class is used to import data from the CEUS-API and saving them in the Drupal database. It also provides the change management functionality described in the system documentation.
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Authors
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Markus Gutmayer - m.gut.nosp@m.maye.nosp@m.r@gma.nosp@m.il.c.nosp@m.om
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
Definition at line 49 of file ceus_importer.inc.php.
Constructor & Destructor Documentation
__construct ()
Constructor.
Creates a new instance of ceus_importer and reads the CEUS API configuration data from Drupal.
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
See also
$sCeusUrl
$sUsername
$sPassword
Definition at line 201 of file ceus_importer.inc.php.
Member Function Documentation
check_return_value ($sReturn) private
Checks the JSON returned by the CEUS API.
This method checks if the CEUS API server responded and if there was an error.
Parameters
string $sReturn JSON encoded string fetched from the CEUS API
Return values
decoded array Success
false An error occurred. The error is stored in the $sError member
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
Definition at line 221 of file ceus_importer.inc.php.
Referenced by connect(), and get_detail().
check_vocabulary ($aCurriculum) private
Checks if a taxonomy vocabulary for the given curriculum exists and creates it if not.
This function stores the corresponding vocabulary (either a new or an existing one) into the $aVocabulary array.
Remarks
This method creates the new vocabulary with the default weight of 10, but only vocabularies with a weight below 0 will be shown publicly.
Parameters
array $aCurriculum Curriculum from CEUS as returned by get_curricula_list()
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
Definition at line 727 of file ceus_importer.inc.php.
connect ()
Connect to CEUS and receive Authtoken.
This function tries to connect to the CEUS-API server and receives and stores the authtoken. Returns true if an authtoken was recieved otherwise it returns false.
Return values
true Connection and authentication successful
false Connection and/or authentication failed
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
Definition at line 247 of file ceus_importer.inc.php.
References check_return_value().
find_nodeid_by_field ($sFieldtype, $sFieldcontent) private
Looks for Drupal content node by title or code.
This function searches for the Drupal content node corresponding to a given course code or course title.
Parameters
string $sFieldtype The name of the field to search in. This can be either "code" or "title".
string $sFieldcontent The search term to look for
Return values
nid The node's id
false No content node with this title or code could be found
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
See also
get_term_ids()
Definition at line 450 of file ceus_importer.inc.php.
get_curricula ()
Main method: Imports curriculum data from CEUS.
This is the main public method of this class. It does the following things:
Reset the statistics
Imports all curricula
Create a new vocabulary if none exists
Load course data from CEUS API
Process relations
Store everything into the Drupal database
Return values
success message The import was successful. This message contains the import statistics.
false An error has occured and the import was not successful.
Authors
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
See also
get_curricula_list()
check_vocabulary()
get_curriculum()
get_details()
process_relations()
Definition at line 691 of file ceus_importer.inc.php.
get_curricula_list () private
Gets a list of all curricula (bachelor, master) from CEUS.
This function retreives a list of all available curricula from the CEUS API.
Returns
Associative array containing all curricula
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
Definition at line 769 of file ceus_importer.inc.php.
get_curriculum ($iID) private
Gets one curriculum tree from CEUS.
This function retreives the complete tree of one certain curriculum from the CEUS API
Parameters
integer $iID CEUS id of the curriculum
Returns
Nested array of course ids
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
Definition at line 787 of file ceus_importer.inc.php.
get_detail ($iID) private
Fetches a single course from CEUS.
This function fetches a single course from the CEUS API and returns all its details in an array.
Parameters
integer $iID CEUS id of the course
Return values
details 2-dimensional array containing the course details. 1. dimension = language, 2. dimension = details.
false An error occured while fetching the details
Authors
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
See also
get_details()
Definition at line 274 of file ceus_importer.inc.php.
References check_return_value().
get_details ($aTree, $iParentID, $iCurriculumID) private
Recursive function that traverses a curriculum tree.
This method goes through all the courses of a curriculum that have been returned by CEUS recursively and reads the details for each course into the $aTerms array. A vocabulary term is created for each item in the respective curriculum.
Parameters
array $aTree The current subtree in the curriculum
integer $iParentID Drupal term id of this course's parent term
integer $iCurriculumID CEUS id of the curriculum this tree belongs to
Return values
true Courses have been read
false The subtree has reached a leaf
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
See also
get_detail()
Definition at line 638 of file ceus_importer.inc.php.
get_error ()
Returns last error message.
This function acts as a public getter for the error message.
Returns
string
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
See also
$sError
Definition at line 804 of file ceus_importer.inc.php.
get_term_ids ($sRelationfield) private
Parses the voraussetzungen field of a course and tries to extract the relation.
This function loops through all links and list items in the voraussetzugnen field and tries to extracts the referenced courses. It does this in 3 steps:
Extract the course names
Try to get the Drupal content node id through the course title
Try to get the Drupal content node id through the course code
Parameters
string $sRelationfield Textual content of the voraussetzungen field as received from CEUS
Returns
Drupal content node ids of related courses
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
See also
find_nodeid_by_field()
parse_link_term_code()
Definition at line 486 of file ceus_importer.inc.php.
has_relation ($sRelationfield) private
Checks if a course has recommendations or prerequisites.
This function determines if a course has a relation with another course. This is the case when the $sRelationfield is not empty and does not begin with "kein" (case insensitive). Returns true if there are any relations that need to be processed. Return false if the arent any.
Parameters
string $sRelationfield Content of the courses voraussetzungen field
Return values
true The course has recommendations or prerequisites
false The course does not have recommendations or prerequisites
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
Definition at line 404 of file ceus_importer.inc.php.
parse_link_term_code ($sLink) private
Parses linked web page and tries to extract a course code.
This function tries to extract the course code (e.g. 1FENKF) from website behind the given $sLink and returns it.
Parameters
string $sLink HTML-Code with Link to CEUS entry
Return values
course code The extracted code
false The extraction was not successful
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
See also
get_term_ids()
Definition at line 423 of file ceus_importer.inc.php.
process_relations () private
Creates Drupal relations out of CEUS relations.
This procedure loops through $aRelations, parses the voraussetzungen field of each course, generates relations for required and suggested courses and stores them in the node
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
See also
get_term_ids()
Definition at line 534 of file ceus_importer.inc.php.
save_node ($aDetail, $tid) private
Saves a course as a Drupal content node.
If a node already exists, the function checks if the changedate has changed. If so, a new version of this conent node is created. If not, nothing is changed
Parameters
array $aDetail Array of course details as returned by get_detail()
array $tid Drupal vocabulary term id of the vocabulary term corresponding to the given course
Returns
Node id of the saved content node
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Authors
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
Definition at line 308 of file ceus_importer.inc.php.
Field Documentation
$aFiles private
Initial value:
= array (
            'AUTH' => 'auth.php',
            'LIST' => 'list.php',
            'CURR' => 'curr.php',
            'DETAIL' => 'detail.php'
    )
Names of the API methods.
This array contains all the API method names for:
Getting an authorization token
Listing all curricula
Getting one curriculum tree
Getting one curriculum item
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
Definition at line 102 of file ceus_importer.inc.php.
$aLanguage private
Initial value:
= array (
            'de',
            'en'
    )
All supported languages.
This array contains the short names of all languages that should be imported.
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
Definition at line 127 of file ceus_importer.inc.php.
$aRelations private
Relations of every course (if available)
This array contains all relations (recommended and needed) in their raw textual form It is filled during the import and evaluated at the end.
The key is the CEUS id of the cours, the value contains the content text of the voraussetzungen field from CEUS.
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
Definition at line 186 of file ceus_importer.inc.php.
$aStats private
Initial value:
= array (
            'loaded' => 0,
            'new' => 0,
            'updated' => 0,
            'numcurrs' => 0,
            'relations' => 0
    )
Import statistics.
This array contains all necessary import statistics, namely:
The number of courses loaded from CEUS
The number of new content nodes created (= new courses)
The number of content nodes that were updated during the import (= changes in CEUS)
The number of curricula loaded from CEUS
the number of relations automatically processed
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit 5ad002c on 2014-07-08
Definition at line 167 of file ceus_importer.inc.php.
$aTerms private
All Terms for vocabularies.
This array contains all the Drupal vocabulary terms associated with the curriculum currently being processed.
The item key represents the CEUS id of one course.
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
Definition at line 152 of file ceus_importer.inc.php.
$aVocabulary private
All vocabularies for current curricula.
This array contains the respective Drupal vocabularies corresponding to the currently imported curricula.
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
Definition at line 140 of file ceus_importer.inc.php.
$sAuthtoken private
CEUS authentication token.
This variable contains the authentication token as retreived from the CEUS API by calling its auth method.
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
Definition at line 88 of file ceus_importer.inc.php.
$sCeusUrl private
Complete URL to CEUS API.
This variable contains the URL to the CEUS API as retreived from the module configuration.
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
Definition at line 58 of file ceus_importer.inc.php.
$sError private
Error message.
If an error has occurred, this variable contains the error message.
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
Definition at line 117 of file ceus_importer.inc.php.
$sPassword private
Password for CEUS API.
This variable contains the password for the CEUS API as retreived from the module configuration.
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
Definition at line 78 of file ceus_importer.inc.php.
$sUsername private
Username for CEUS API.
This variable contains the username for the CEUS API as retreived from the module configuration.
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
Definition at line 68 of file ceus_importer.inc.php.
The documentation for this class was generated from the following file:
ceus_importer.inc.php