stukowin: overviewPDF Class Reference
overviewPDF Class Reference
Drupal2PDF
Class for PDF document generation from curricula data.
Public Member Functions
Footer ()
Generates Footer for each page.
createPDF ($iVID)
Creates the PDF document.
Error ($msg)
Throws exception in case of an error.
Private Member Functions
getNextIndex ($iLevel)
Gets index of the desired level.
getTotalY ()
Gets the full y-position in the document.
createTOCPage ()
Adds a table of contents page to the PDF document.
getUniqueFilename ($sCurrType, $sCurrVersion)
Creates a unique filename.
printCurriculum ($oCurriculum)
Prints a curriculum object and all its courses to the PDF document.
printTopLevel ($oTopLevel)
Decides whether to print a structural element or a subject.
printFach ($oFach)
Prints a subject to the PDF document.
generateTableRecHelper ($oCourse)
Recursive function for generating overview table.
splitBoldTextIntoLines ($sText, $iMaxWidth)
Inserts line breaks into bold text.
splitRecHelper ($aWords, $iCurrIndex, $iMaxWidth)
Recursive helper function for splitBoldTextIntoLines()
printZieleInhalte ($oCourse)
Prints the course goals and content of teaching and their respecitve headings to the document.
printHeading ($sText, $iLevel, $bShowIndex=true, $sAlign= 'L', $bAddBookmark=true)
Prints a heading to the PDF document.
Static Private Member Functions
static getHTMLHeight ($sHTML)
Determines height of HTML Code.
static getCourses ($currId)
Gets all courses for a given curriculum id.
static assertAttributes ($oCourse)
Guarantees the existence of the specified attributes in the course and all its children.
static convertStringToValidFilename ($sString)
Utility method that formats a string into a valid file name.
Private Attributes
$aIndices = array ()
Array of indices for continuous indexation of headings.
Detailed Description
Class for PDF document generation from curricula data.
This class provides the functionality for automatically generating a PDF document from a curriculum.
It is publicly accessible through the createPDF() method, which initiates and guides the PDF generation.
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Authors
Fabian Puehringer - f.pue.nosp@m.hrin.nosp@m.ger@2.nosp@m.4spe.nosp@m.ed.at
Version
1.0.3 2014-07-22
Since
Commit b9342d9 on 2014-06-30
See also
createPDF()
Definition at line 62 of file pdf_creator.inc.php.
Member Function Documentation
static assertAttributes ($oCourse) static private
Guarantees the existence of the specified attributes in the course and all its children.
This is a recursive helper method which asserts that the following attributes exist in the course object:
title
ects
wst
lvatype
typename
ziele
lehrinhalte
lvtypshort
typename
Needed so that the other methods do not have to check everytime an attribute is accessed.
Parameters
object $oCourse The course to assert the attributes for
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit b9342d9 on 2014-06-30
Definition at line 638 of file pdf_creator.inc.php.
Referenced by getCourses().
static convertStringToValidFilename ($sString) static private
Utility method that formats a string into a valid file name.
Parameters
string $sString The file name to validate
Returns
The valid file name created from the input
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit f157d51 on 2014-07-06
Definition at line 672 of file pdf_creator.inc.php.
Referenced by getUniqueFilename().
createPDF ($iVID)
Creates the PDF document.
This method is the main public method of the overviewPDF class. It manages the entire document generation and saves the PDF to the preconfigured path. The steps for creating the document are as follows:
Set up PDF document
Set document meta information
Set up title page
Initiate printing of individual subjects
Add index page
Save the document
Parameters
integer $iVID Drupal vocabulary id of the desired Curriculum
Returns
Success message: 'PDF successfully created at ' and the filepath
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit b9342d9 on 2014-06-30
See also
stukowin_pdf_menu()
stukowin_pdf_menu_submit()
Definition at line 195 of file pdf_creator.inc.php.
References createTOCPage(), and printCurriculum().
createTOCPage () private
Adds a table of contents page to the PDF document.
This method is called at the end of the document creation, after all subjects have been printed to the document, and inserts a table of contents (index) page as the second page in the document.
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit b9342d9 on 2014-06-30
See also
TCPDF::addTOCPage()
printHeading()
Definition at line 262 of file pdf_creator.inc.php.
Referenced by createPDF().
Error ($msg)
Throws exception in case of an error.
This method is needed for displaying errors as drupal messages, due to TCPDF normally displaying errors by itself and the dying.
Parameters
string $msg The error message to throw the ecxeption with
Exceptions
Exception A new exception with the given message
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit e4fa523 on 2014-07-02
See also
TCPDF::Error()
Definition at line 245 of file pdf_creator.inc.php.
Footer ()
Generates Footer for each page.
This method draws a 1px line across the entire page 15mm above the bottom and writes the page number in the format "current page/total pages" into the bottom right corner.
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit b9342d9 on 2014-06-30
See also
TCPDF::Footer()
Definition at line 86 of file pdf_creator.inc.php.
generateTableRecHelper ($oCourse) private
Recursive function for generating overview table.
This is a recursive helper function for generating a subject overview table. It traverses the nested array of courses down to the leaves and creates a table row for each course.
Subjects are printed in bold
Modules are printed in italics
Courses are printed in normal text
Parameters
object $oCourse The course to generate the table HTML code for
Returns
The HTML code of the table rows for this course and all its children
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit b9342d9 on 2014-06-30
See also
printFach()
Definition at line 454 of file pdf_creator.inc.php.
References splitBoldTextIntoLines().
Referenced by printFach().
static getCourses ($currId) static private
Gets all courses for a given curriculum id.
This method gets all the courses in a curriculum and prepares them for further processing in the PDF creation process.
Parameters
integer $currId The vocabulary id of the curriculum to get the courses from
Returns
The nested array of all courses in the given curriculum
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit b9342d9 on 2014-06-30
Definition at line 608 of file pdf_creator.inc.php.
References assertAttributes().
Referenced by printCurriculum().
static getHTMLHeight ($sHTML) static private
Determines height of HTML Code.
This utility method prints $sHTML to a test instance of overviewPDF and determines what height the HTML code has if printed.
This method is needed for evaluating whether an HTML table would fit into the remaining space on the page or if it would be broken into two pages.
Returns
The height of the HTML code
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit b9342d9 on 2014-06-30
See also
printFach()
Definition at line 141 of file pdf_creator.inc.php.
Referenced by printFach().
getNextIndex ($iLevel) private
Gets index of the desired level.
This utility method manages the $aIndices array and determines what heading index comes next in the given $iLevel (e.g. 1, 2, 3 etc.).
If some levels have been skipped (e.g. the first call to this method is with $iLevel = 3), it fills up the missing array values with 1.
After it has determined the correct index, it increments the corresponding value in the array by 1.
Parameters
integer $iLevel Level for which the index is wanted
Returns
The next index on the given level. One single integer (i.e. not "1.1.2")
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit b9342d9 on 2014-06-30
Definition at line 113 of file pdf_creator.inc.php.
Referenced by printHeading().
getTotalY () private
Gets the full y-position in the document.
This utility method determines the current y position in relation to the beginning of the document, not just the current page (like TCPDF::GetY()), excluding top and bottom margins.
This method is needed to compare positions in the document across pages.
Returns
Full y-position in the entire document (not just on this page), excluding margins
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit b9342d9 on 2014-06-30
See also
getHTMLHeight()
TCPDF::GetY()
Definition at line 168 of file pdf_creator.inc.php.
getUniqueFilename ($sCurrType, $sCurrVersion) private
Creates a unique filename.
Determines if a file with the standard filename as defined in the module settings already exists. If one exists, it appends a number and increases it until the name is not already taken.
Also, it creates the directory into which the document should be saved according to the module settings (if it does not already exist).
Parameters
string $sCurrType The type of the curriculum (Bachelorstudium, Masterstudium)
string $sCurrVersion The version of the curriculum (e.g. 2013W)
Returns
The unique filename
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit e8704fd on 2014-06-30
See also
stukowin_admin()
Definition at line 291 of file pdf_creator.inc.php.
References convertStringToValidFilename().
printCurriculum ($oCurriculum) private
Prints a curriculum object and all its courses to the PDF document.
This method does the following things:
Print the curriculum name as a heading
Create an overview table with all the subjects it contains
Print the details of each subject to the document
Parameters
object $oCurriculum The curriculum object to print
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit b9342d9 on 2014-06-30
Definition at line 328 of file pdf_creator.inc.php.
References getCourses(), printHeading(), and printTopLevel().
Referenced by createPDF().
printFach ($oFach) private
Prints a subject to the PDF document.
This method prints the subject title and details, an overview of all its subcourses and their details to the document.
Parameters
object $oFach The course object to print
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit b9342d9 on 2014-06-30
Definition at line 398 of file pdf_creator.inc.php.
References generateTableRecHelper(), getHTMLHeight(), printHeading(), and printZieleInhalte().
Referenced by printTopLevel().
printHeading ($sText, $iLevel, $bShowIndex = true, $sAlign = 'L', $bAddBookmark = true) private
Prints a heading to the PDF document.
This method manages headings in the document. It automatically indexes the headings using getNextIndex() and optionally adds a bookmark for it.
Parameters
string $sText The heading text
int $iLevel The level at which the heading should be created and the bookmark set
boolean $bShowIndex true if the index should be shown in the heading
string $sAlign Alignment of the heading. For allowed values see TCPDF::MultiCell()
boolean $bAddBookmark true if heading should be shown on the index page and bookmarked
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit b9342d9 on 2014-06-30
See also
createTOCPage()
getNextIndex()
Definition at line 587 of file pdf_creator.inc.php.
References getNextIndex().
Referenced by printCurriculum(), printFach(), and printTopLevel().
printTopLevel ($oTopLevel) private
Decides whether to print a structural element or a subject.
This is a dispatcher method that checks if an object is a structural element (1. Semester, 2. Semester etc.) or a course. If calls printHeading() if it is a structural element and then printFach() for all its children or just printFach() if it is a course object.
Parameters
object $oTopLevel The object to check
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit a311596 on 2014-07-02
Definition at line 376 of file pdf_creator.inc.php.
References printFach(), and printHeading().
Referenced by printCurriculum().
printZieleInhalte ($oCourse) private
Prints the course goals and content of teaching and their respecitve headings to the document.
If one of them is not set or empty, their heading is not printed either.
Parameters
object $oCourse The course to print the goals and contents for
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit b9342d9 on 2014-06-30
See also
printFach()
Definition at line 546 of file pdf_creator.inc.php.
Referenced by printFach().
splitBoldTextIntoLines ($sText, $iMaxWidth) private
Inserts line breaks into bold text.
This method breaks the $sText into separate lines which are shorter than $iMaxWidth if printed as bold text. If one word alone is too long or the entire string is shorter than $iMaxWidth, it is not splitted.
This method is needed in generateTableRecHelper() because TCPDF does not break the words correctly in a table if the text is written in a <B> tag. This caused issues where text would overflow its table cell to the right by a few cm.
Parameters
string $sText The text to split
$iMaxWidth The The maximum width a line is allowed to have
Returns
The $sText with <br> tags inserted whenever necessary
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit 7e5b545 on 2014-07-06
Definition at line 498 of file pdf_creator.inc.php.
References splitRecHelper().
Referenced by generateTableRecHelper().
splitRecHelper ($aWords, $iCurrIndex, $iMaxWidth) private
Recursive helper function for splitBoldTextIntoLines()
Parameters
array $aWords The array of words as split in splitBoldTextIntoLines()
integer $iCurrIndex The current index in the array
integer $iMaxWidth The maximum width a line is allowed to have
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit 7e5b545 on 2014-07-06
See also
splitBoldTextIntoLines()
Definition at line 520 of file pdf_creator.inc.php.
Referenced by splitBoldTextIntoLines().
Field Documentation
$aIndices = array () private
Array of indices for continuous indexation of headings.
Every key in this array represents an indexation level (e.g. level 2 for 1.1, level 3 for 1.1.1) and every value in the array the current index for that level.
Since
Commit b9342d9 on 2014-06-30
See also
getNextIndex()
Definition at line 73 of file pdf_creator.inc.php.
The documentation for this class was generated from the following file:
pdf_creator.inc.php