stukowin: graph.js File Reference
graph.js File Reference
Drupal2AGG
Script for nicely displaying CEUS data.
Functions
jQuery (document).ready(function()
Gets a list of all courses.
function getCurricula (data)
Extracts curricula from JSON.
function fill_crclm (data)
Extracts top-level courses and fills page with content.
function showEmpfohlen (element)
Shows or hides recommended courses.
function showVoraussetzungen (element)
Shows or hides required courses.
function expand_reduce (element)
Toggles the expansion/reduction of a course <div>
function expand_all ()
Expands all divs.
function reduce_all ()
Reduces all divs.
function expandAndScrollToElement (element, highlightColor)
Expands the curriculum tree down to an element.
function createDivs (kurs, level)
Creates the <div>s for all courses recursively.
function createTds (kurs)
Creates the header table cells.
function isFullyVisible (elem)
Checks if an element is fully visible.
function buildRequestURL (baseUrl, type, curriculums)
Creates the JSON request URL.
function clearDiv ()
Empties main <div>
function addResources ()
Adds missing stylesheets and the jQuery effect library.
function fillMissingDetail (data)
Fetches course data for missing courses.
Variables
var kurse = {}
var drupal_root = ""
var jsonCalls = []
Detailed Description
Script for nicely displaying CEUS data.
This script is responsible for creating the proper html/css/js needed for displaying the graphical representation of CEUS data.
In order for this script to work, a <div> with the id "main" and the tags data-currtype and data-curriculums set needs to be present on the page. Example:
<div id="main" data-currtype="Bachelorstudium" data-curriculums="curriculum itsv specialisation">
</div>
The graphical representation will look approximately like this:
Graphical Display
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Authors
Markus Gutmayer - m.gut.nosp@m.maye.nosp@m.r@gma.nosp@m.il.c.nosp@m.om
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Version
1.0 2014-07-09
Since
Commit f90560a on 2014-06-28
Definition in file graph.js.
Function Documentation
function addResources ()
Adds missing stylesheets and the jQuery effect library.
This utility procedure adds the curriculum_style.css stylesheet and the jQuery effect library to the document.
Author
Markus Gutmayer - m.gut.nosp@m.maye.nosp@m.r@gma.nosp@m.il.c.nosp@m.om
Authors
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Since
Commit 9f5e8a6 on 2014-07-05
Definition at line 645 of file graph.js.
References drupal_root, and jQuery().
Referenced by jQuery().
function buildRequestURL (baseUrl, type, curriculums)
Creates the JSON request URL.
This utility function buils the URL for the JSON request based on the main <div>s data tags.
Parameters
baseUrl Drupal base URL to build the request on (Needed because drupal could be installed under a sub path)
type The curriculum type to get ("Bachelorstudium","Masterstudium")
curriculums The vocabulary types to get ("curriculum", "itsv" and/or "specialisation")
Returns
The complete request URL
Author
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Authors
Markus Gutmayer - m.gut.nosp@m.maye.nosp@m.r@gma.nosp@m.il.c.nosp@m.om
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit 58e2eac on 2014-07-02
Definition at line 604 of file graph.js.
Referenced by jQuery().
function clearDiv ()
Empties main <div>
This utility procedure deletes all <div> contents except for the curriculum legend.
Author
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Authors
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit 58e2eac on 2014-07-02
Definition at line 630 of file graph.js.
References jQuery().
Referenced by fill_crclm().
function createDivs (kurs, level)
Creates the <div>s for all courses recursively.
This function creates the entire content of the graphical display recursively. For each course it creates a header table and its children.
Parameters
kurs The course to create the <div> for
level The current recursion level (needed in order to decide if the element is top-level or not
Returns
The complete HTML for the given course's <div>
Authors
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Markus Gutmayer - m.gut.nosp@m.maye.nosp@m.r@gma.nosp@m.il.c.nosp@m.om
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Since
Commit 3372f36 on 2014-06-29
Definition at line 459 of file graph.js.
References createTds(), jQuery(), and kurse.
Referenced by fill_crclm().
function createTds (kurs)
Creates the header table cells.
This utility function creates the table cells in the header used in all course, module and subject <div>s. It also requests the details of all courses referenced (as recommendation/prerequisite) but not included in the loaded vocabulary.
Parameters
kurs The course to create the cells for
Returns
The HTML code for the <td>s in the header
Author
Markus Gutmayer - m.gut.nosp@m.maye.nosp@m.r@gma.nosp@m.il.c.nosp@m.om
Authors
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Since
Commit 15c1f4d on 2014-06-30
Definition at line 515 of file graph.js.
References drupal_root, fillMissingDetail(), jQuery(), jsonCalls, and kurse.
Referenced by createDivs().
function expand_all ()
Expands all divs.
This procedure expands all divs that are currently reduced.
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit 3372f36 on 2014-06-29
Definition at line 383 of file graph.js.
References expand_reduce(), and jQuery().
function expand_reduce (element)
Toggles the expansion/reduction of a course <div>
This procedure expands/reduces a course <div>, thus showing or hiding its children.
Parameters
element The element to expand/reduce
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit 3372f36 on 2014-06-29
Definition at line 344 of file graph.js.
References drupal_root, and jQuery().
Referenced by expand_all(), expandAndScrollToElement(), jQuery(), and reduce_all().
function expandAndScrollToElement (element, highlightColor)
Expands the curriculum tree down to an element.
This procedure expands the curriculum tree down to the given element, scrolls to it and then highlights it in the given highlightColor.
Parameters
element The element to expand and scroll to
highlightColor The color to highlight the element in. Default is #90EE90.
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit 3372f36 on 2014-06-29
Definition at line 417 of file graph.js.
References expand_reduce(), isFullyVisible(), and jQuery().
Referenced by jQuery().
function fill_crclm (data)
Extracts top-level courses and fills page with content.
This event handler extracts the top-level courses out of the JSON-data and fills the page with content by calling createDivs().
Parameters
data The received JSON file containing the curriculum tree
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Authors
Markus Gutmayer - m.gut.nosp@m.maye.nosp@m.r@gma.nosp@m.il.c.nosp@m.om
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Since
Commit f90560a on 2014-06-28
Definition at line 223 of file graph.js.
References clearDiv(), createDivs(), jQuery(), kurse, and reduce_all().
Referenced by getCurricula().
function fillMissingDetail (data)
Fetches course data for missing courses.
This utility procedure and event handler is used for fetching the details of all those courses that are not included in the display but referenced as recommendation and/or prerequisite.
Parameters
data The received JSON details array of one course
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit f157d51 on 2014-07-06
Definition at line 673 of file graph.js.
References kurse.
Referenced by createTds().
function getCurricula (data)
Extracts curricula from JSON.
This event handler extracts the curricula out of the JSON data, fills the select box at the top of the page and calls fill_crclm() for the first curriculum.
Parameters
data The received JSON file containing the curricula list
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Authors
Markus Gutmayer - m.gut.nosp@m.maye.nosp@m.r@gma.nosp@m.il.c.nosp@m.om
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Since
Commit f90560a on 2014-06-28
Definition at line 168 of file graph.js.
References drupal_root, fill_crclm(), jQuery(), and jsonCalls.
Referenced by jQuery(), stukowin_pdf_menu(), and stukowin_taxonomy_menu().
function isFullyVisible (elem)
Checks if an element is fully visible.
This utility function determines if an element is fully visible on the screen
Parameters
elem The element to check
Return values
true The element is fully visible
false The element is not fully visible
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit 3372f36 on 2014-06-29
Definition at line 573 of file graph.js.
References jQuery().
Referenced by expandAndScrollToElement().
jQuery (document)
Gets a list of all courses.
This event handler gets a list of all courses from stukowin module's JSON service and sets up event handlers for different events.
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Authors
Markus Gutmayer - m.gut.nosp@m.maye.nosp@m.r@gma.nosp@m.il.c.nosp@m.om
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Since
Commit f90560a on 2014-06-28
Definition at line 89 of file graph.js.
References addResources(), buildRequestURL(), drupal_root, expand_reduce(), expandAndScrollToElement(), getCurricula(), showEmpfohlen(), and showVoraussetzungen().
Referenced by addResources(), clearDiv(), createDivs(), createTds(), expand_all(), expand_reduce(), expandAndScrollToElement(), fill_crclm(), getCurricula(), isFullyVisible(), reduce_all(), showEmpfohlen(), and showVoraussetzungen().
function reduce_all ()
Reduces all divs.
This procedure reduces all divs that are currently expanded.
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Since
Commit d831fad on 2014-07-03
Definition at line 397 of file graph.js.
References expand_reduce(), and jQuery().
Referenced by fill_crclm().
function showEmpfohlen (element)
Shows or hides recommended courses.
This click handler shows or hides the list of recommended courses for a given course.
Parameters
element The element to show the recommended courses for
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Authors
Markus Gutmayer - m.gut.nosp@m.maye.nosp@m.r@gma.nosp@m.il.c.nosp@m.om
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Since
Commit 3372f36 on 2014-06-29
Definition at line 256 of file graph.js.
References jQuery(), and kurse.
Referenced by jQuery().
function showVoraussetzungen (element)
Shows or hides required courses.
This click handler shows or hides the list of required courses for a given course.
Parameters
element The element to show the required courses for
Author
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Authors
Markus Gutmayer - m.gut.nosp@m.maye.nosp@m.r@gma.nosp@m.il.c.nosp@m.om
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Since
Commit 3372f36 on 2014-06-29
Definition at line 300 of file graph.js.
References jQuery(), and kurse.
Referenced by jQuery().
Variable Documentation
var drupal_root = ""
Definition at line 75 of file graph.js.
Referenced by addResources(), createTds(), expand_reduce(), getCurricula(), and jQuery().
var jsonCalls = []
Definition at line 76 of file graph.js.
Referenced by createTds(), and getCurricula().
var kurse = {}
Definition at line 74 of file graph.js.
Referenced by createDivs(), createTds(), fill_crclm(), fillMissingDetail(), showEmpfohlen(), and showVoraussetzungen().