stukowin: Module Core
Module Core
Module that contains core functionality.
Files
file content_manager.inc.php
Access to curricula data.
file stukowin.install
Install script.
Data Structures
class content_manager
Access to drupal vocabularies and content nodes.
Functions
stukowin_install ()
Implements hook_install().
_stukowin_installed_taxonomy_fields ()
Contains the array of additional vocabulary fields.
_stukowin_installed_taxonomy_instances ()
Contains the array of additional fields for vocabulary instances.
_stukowin_installed_fields ()
Contains the array of additional fields for the stukowin content node type.
_stukowin_installed_instances ()
Contains the array of additional fields for the stukowin content node type.
_stukowin_relation_types ()
Contains custom relation types for recommendations and requirements.
_stukowin_create_relation_types ()
Creates the relation type.
stukowin_uninstall ()
Implements hook_uninstall().
stukowin_admin ()
Menu callback for module settings ("admin/stukowin/settings")
stukowin_menu ()
Implements hook_menu().
Detailed Description
Module that contains core functionality.
This module contains all files, classes and methods that provide the core functionality of the Drupal module. The members of this group ensure a working cooperation between all of the components and Drupal.
Authors
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Markus Gutmayer - m.gut.nosp@m.maye.nosp@m.r@gma.nosp@m.il.c.nosp@m.om
Function Documentation
_stukowin_create_relation_types ()
Creates the relation type.
This method creates the relation type for course recommendations and requirements
Version
1.0.0 2014-07-07
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
Definition at line 629 of file stukowin.install.
References _stukowin_relation_types().
Referenced by stukowin_install().
_stukowin_installed_fields ()
Contains the array of additional fields for the stukowin content node type.
Return a structured array defining the fields created by this content type. The additional fields are:
ceusid
code
ects
wst
verantname
verantemail
changedate
lvtypname
lvtypshort
lvatype
typename
ziele
lehrinhalte
voraussetzungen
voraussetzung
empfehlung
term of the course as received from CEUS and saved in Drupal.
Returns
A structured array for Drupal field generation
Version
1.0.0 2014-07-07
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
Definition at line 209 of file stukowin.install.
Referenced by content_manager::get_return_node(), stukowin_install(), stukowin_uninstall(), and content_manager::taxonomy_get_nested_tree().
_stukowin_installed_instances ()
Contains the array of additional fields for the stukowin content node type.
Return a structured array defining and describing in greater detail the fields created by this content type. The additional fields are:
ceusid
code
ects
wst
verantname
verantemail
changedate
lvtypname
lvtypshort
lvatype
typename
ziele
lehrinhalte
voraussetzungen
voraussetzung
empfehlung
term of the course as received from CEUS and saved in Drupal.
Returns
A structured array for Drupal field generation
Version
1.0.0 2014-07-07
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Authors
Fabian Puehringer - f.pue.nosp@m.hrin.nosp@m.ger@2.nosp@m.4spe.nosp@m.ed.at
Since
Commit d179abc on 2014-06-28
Definition at line 334 of file stukowin.install.
Referenced by stukowin_install().
_stukowin_installed_taxonomy_fields ()
Contains the array of additional vocabulary fields.
Returns a structured array defining the custom fields for vocabularies. The additional fields are:
faculty
version
type of curriculum as received from CEUS.
Returns
A structured array for Drupal field generation
Version
1.0.0 2014-07-07
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
See also
_stukowin_installed_taxonomy_instances()
Definition at line 103 of file stukowin.install.
Referenced by stukowin_install(), and stukowin_uninstall().
_stukowin_installed_taxonomy_instances ()
Contains the array of additional fields for vocabulary instances.
Returns a structured array defining and describing in greater detail the custom fields for vocabularies. The additional fields are:
faculty
version
type of curriculum as received from CEUS.
Returns
A structured array for drupal field instance generation
Version
1.0.0 2014-07-07
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
See also
_stukowin_installed_taxonomy_fields()
Definition at line 147 of file stukowin.install.
Referenced by stukowin_install().
_stukowin_relation_types ()
Contains custom relation types for recommendations and requirements.
Returns
An array containing the description for recommended and required prerequisite relations.
Version
1.0.0 2014-07-07
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Since
Commit d179abc on 2014-06-28
Definition at line 607 of file stukowin.install.
Referenced by _stukowin_create_relation_types(), and stukowin_uninstall().
stukowin_admin ()
Menu callback for module settings ("admin/stukowin/settings")
Form for administration of the module settings This form has the following input fields:
CEUS API Settings
URL to CEUS API
Username for CEUS API
Password for CEUS API
Last Update from CEUS API
PDF Settings
PDF Path
PDF generic name
Returns
An array containing the form structure
Authors
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
Definition at line 105 of file stukowin.module.
stukowin_install ()
Implements hook_install().
Sets up drupal for use with the stukowin module.
Creates the content type for LVA nodes.
Creates relation types for requirements and recommendations.
Adds 3 fields to taxonomy nodes for faculty, version and type of curriculum
Authors
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Version
1.0.0 2014-07-07
Since
Commit d179abc on 2014-06-28
Definition at line 30 of file stukowin.install.
References _stukowin_create_relation_types(), _stukowin_installed_fields(), _stukowin_installed_instances(), _stukowin_installed_taxonomy_fields(), and _stukowin_installed_taxonomy_instances().
stukowin_menu ()
Implements hook_menu().
Registers all menu links with Drupal. The following links are registered:
CEUS API Settings @ 'admin/stukowin/settings'
CEUS Data import @ 'admin/settings/stukowin/import'
PDF Generation @ 'admin/settings/stukowin/pdf'
ITSV/Specialisation Taxonomy Creation @ 'admin/settings/stukowin/taxonomy'
Curriculum JSON Service @ 'stukowin/crclm'
Curricula List JSON Service @ 'stukowin/crclmlst'
Course Detail JSON Service @ 'stukowin/lva'
Authors
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Version
1.0.0 2014-07-16
Since
Commit d179abc on 2014-06-28
See also
stukowin_pdf_menu()
stukowin_taxonomy_menu()
stukowin_pre_retreive()
stukowin_admin()
stukowin_get_lva()
stukowin_get_crclm_taxonomy()
stukowin_get_crclm_list()
Definition at line 507 of file stukowin.module.
stukowin_uninstall ()
Implements hook_uninstall().
Deletes all content nodes
Deletes all CEUS taxonomies
Deletes the content type for LVA nodes
Version
1.0.0 2014-07-09
Author
Konstantinos Dafalias - kdafa.nosp@m.lias.nosp@m.@gmai.nosp@m.l.co.nosp@m.m
Jakob Strasser - jakob.nosp@m..str.nosp@m.asser.nosp@m.@tel.nosp@m.enet..nosp@m.be
Werner Breuer - blues.nosp@m.cree.nosp@m.nwern.nosp@m.er@g.nosp@m.mail..nosp@m.com
Since
Commit 2506486 on 2014-07-09
Definition at line 662 of file stukowin.install.
References _stukowin_installed_fields(), _stukowin_installed_taxonomy_fields(), and _stukowin_relation_types().